# Generated by Django 2.0.2 on 2018-03-06 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('pub_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 9, 13, 33, 395003, tzinfo=utc), verbose_name='publish time')),
                ('edited_time', models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 6, 9, 13, 33, 395003, tzinfo=utc), verbose_name='Edit time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Author')),
            ],
        ),
    ]
