# Generated by Django 2.0.2 on 2018-03-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_time',
            field=models.DateTimeField(verbose_name='publish time'),
        ),
    ]
