# Generated by Django 2.0.2 on 2018-03-06 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 6, 9, 14, 20, 263439, tzinfo=utc), verbose_name='Edit time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 9, 14, 20, 263439, tzinfo=utc), verbose_name='publish time'),
        ),
    ]
