# Generated by Django 2.0.2 on 2018-03-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Permission', models.IntegerField(choices=[(1, 'ADD'), (2, 'EDIT'), (3, 'DELETE')], max_length=1)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Permission', models.IntegerField(choices=[(1, 'ADMIN'), (2, 'PUBLISHER'), (3, 'APPROVER'), (4, 'MODERATOR'), (5, 'EDITOR'), (6, 'CREATOR')], max_length=1)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('PassWord', models.CharField(max_length=100)),
                ('BirthDay', models.DateField()),
                ('FullName', models.CharField(blank=True, max_length=100)),
                ('Hobbies', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Group')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Role')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ManyToManyField(through='user.UserRole', to='user.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(through='user.UserGroup', to='user.User'),
        ),
    ]
